In [8]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [2]:
x = tf.placeholder(tf.float32, shape=(2,3))
y = tf.placeholder(tf.float32, shape=(2,1))
linear_model = tf.layers.Dense(units=1)
_y = linear_model(x)

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
loss = tf.losses.mean_squared_error(labels=y, predictions=_y)
train_op = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(loss)

Instructions for updating:
Use tf.cast instead.


In [11]:
data_x = np.random.rand(2,3)
data_y = np.random.rand(2,1)
print(data_x)
print(data_y)

[[0.54751019 0.96372371 0.72836711]
 [0.2083336  0.49237958 0.08091608]]
[[0.1584483 ]
 [0.73940728]]


In [19]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
for epoch in range(1000):
    _, cost = sess.run([train_op, loss], feed_dict={x:data_x, y:data_y})
    if (epoch+1) % 100 == 0:
        print('epoch: %s - cost: %s' %(epoch+1, cost))
print(sess.run(_y, feed_dict={x:data_x}))

epoch: 100 - cost: 0.04361044
epoch: 200 - cost: 0.027926091
epoch: 300 - cost: 0.017891776
epoch: 400 - cost: 0.011462932
epoch: 500 - cost: 0.0073441286
epoch: 600 - cost: 0.004705279
epoch: 700 - cost: 0.003014581
epoch: 800 - cost: 0.0019313847
epoch: 900 - cost: 0.0012373991
epoch: 1000 - cost: 0.0007927863
[[0.18008888]
 [0.70608747]]


In [26]:
g = tf.get_default_graph()

In [30]:
tf.GraphKeys.GLOBAL_VARIABLES

'variables'

In [31]:
g.building_function

False

In [32]:
g.collections

[('__varscope',),
 ('__variable_store',),
 'trainable_variables',
 'variables',
 'update_ops',
 'losses',
 'train_op']

In [33]:
g.version

123

In [37]:
with tf.name_scope('scope1'):
    with tf.name_scope(None):
        with tf.name_scope('scope3'):
            print(tf.get_default_graph().get_name_scope())

scope3


In [50]:
a = tf.constant(1, shape=[2,3], dtype=tf.float32)
print(cons.graph == tf.get_default_graph())

True


In [51]:
g0 = tf.Graph()
with g0.as_default():
    b = tf.constant(1, shape=[2,3], dtype=tf.float32)
print(b.graph == tf.get_default_graph())
print(b.graph == g0)

False
True


In [53]:
with tf.Graph().as_default() as g1:
    c = tf.constant(1, shape=[2,3], dtype=tf.float32)
print(c.graph == tf.get_default_graph())
print(c.graph == g0)
print(c.graph == g1)

False
False
True
